# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - Canada.Rmd
      - .github/workflows/data_update_bot.yml
  schedule:
    - cron: "30 7,23 * * *"

name: Update data

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  render:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-R@v1    
      - name: Setting up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages("devtools")
          install.packages("knitr")
          install.packages("plotly")
          install.packages("tidyverse")
          install.packages("rgeos")
          install.packages("zoo")
          install.packages("lubridate")
          install.packages("rmarkdown")
          install.packages("sf")
          install.packages("viridis")
          install.packages("rnaturalearth")
          devtools::install_github("ropensci/rnaturalearthhires")
        shell: Rscript {0}
      - name: Update data and render html
        run: |
          rmarkdown::render("Canada.Rmd")
        shell: Rscript {0}
      - id: get-date
        run: echo "::set-output name=value::$(date --iso-8601)"  
      - name: Commit results
        uses: EndBug/add-and-commit@v7
        with:
          add: 'Canada.html'
          default_author: github_actions
          message: "Bot: Update data ${{ steps.get-date.outputs.value }}" 
 
        
